# ---- Stage 1: Build the application ----
FROM maven:3.6.3-jdk-8 AS builder

# Set working directory
WORKDIR /app

# Copy the project files
COPY pom.xml .
COPY src ./src

# Package the application
RUN mvn clean package -DskipTests

# ---- Stage 2: Run the application ----
FROM openjdk:8-jdk-alpine

# Set working directory
WORKDIR /app

# Copy the jar from the builder stage
COPY --from=builder /app/target/springboot-k8s-mysql-0.0.1-SNAPSHOT.jar app.jar

COPY opentelemetry-javaagent.jar opentelemetry-javaagent.jar

# Expose port (optional, adjust if needed)
EXPOSE 8080

# Command to run the application
#ENTRYPOINT ["java", "-jar", "app.jar"]

ENTRYPOINT ["java", \
            "-javaagent:/app/opentelemetry-javaagent.jar", \
            "-Dotel.javaagent.enabled=true", \
            "-Dotel.exporter.otlp.endpoint=http://<COLLECTOR_HOST>:<COLLECTOR_PORT>", \
            "-Dotel.service.name=my-spring-boot-app", \
            "-jar", "/app/app.jar"]


